### ISSUE TITLE
нверчик

### ISSUE THREAD

**Issue by HiPriv228** [allsystemsaregood/allsystemsaregood.github.io#1]
![photo_2022-04-30_15-05-42](https://user-images.githubusercontent.com/75212472/166101191-b5b33bcf-3d96-4807-a4f3-4f51297f68a1.jpg)

**Comment by allsystemsaregood** [comment]
### 

1. > [`_**нверчик**_`](url)

**Comment by macintoshkernel** [comment]
какой сладкий
